### ISSUE TITLE
Rename and re-order headers on Resources tab

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#10]
Change order and headers on [Resources tab](https://livingatlas.arcgis.com/policy/resources/) to:

New order:

Header: Start here 
Subheader: Learn how to find and share ready-to-use policy maps about your community 
Policy group Resources category: Getting started 

Header: Get inspired 
Subheader: Find examples from others to kickstart your own policy maps 
Policy group Resources category: Best Practices 

Header: Apply a policy perspective 
Subheader: Create your own maps that show opportunities to intervene 
Policy group Resources category: Learn Lessons 

Header: Community perspectives  
Subheader: None
Policy group Resources category: Industry perspectives

**Comment by vannizhang** [comment]
@lisaberrygis Fixed, please test on DEV: https://livingatlasdev.arcgis.com/policy/resources/

**Comment by lisaberrygis** [comment]
Looks good. No issues.
