### ISSUE TITLE
Give item cards special item type label 

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#12]
For items that are tagged with a special item type, label the items by the special item type category. For items without the special item type tag, use the default ArcGIS Online item type.  This applies only to items on both the Resources tab and the Overview tab.

For example, instead of "Application" 
![image](https://user-images.githubusercontent.com/12399083/111703711-4212c700-87fb-11eb-91dd-9f26c4e5e051.png)

If the item is tagged with an item type, use that:
![image](https://user-images.githubusercontent.com/12399083/111703739-4ccd5c00-87fb-11eb-87bd-78953e5ffdcd.png)

**Comment by vannizhang** [comment]
@lisaberrygis Fixed, please test on DEV: https://livingatlasdev.arcgis.com/policy/resources/

**Comment by lisaberrygis** [comment]
This is a big improvement! 

I didn't find any issues, but will go ahead and chat with the team about adding these to all/most items so that we don't have things like this:
![image](https://user-images.githubusercontent.com/12399083/112062626-66cdae00-8b1d-11eb-8b5c-88348056c1b7.png)
