### ISSUE TITLE
Move rotation arrows on Resources tab

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#13]
For the different items in each rotation, move the arrows from below the list to beside.

For example, currently the arrows are here:
![image](https://user-images.githubusercontent.com/12399083/111703915-93bb5180-87fb-11eb-8614-d88bc809bd33.png)

But ideally they would be here (like they are on the Overview page):
![image](https://user-images.githubusercontent.com/12399083/111703994-b2b9e380-87fb-11eb-8487-9c2af9d7cc65.png)

**Comment by vannizhang** [comment]
@lisaberrygis Fixed, please test on DEV: https://livingatlasdev.arcgis.com/policy/resources/

**Comment by lisaberrygis** [comment]
Looks great. No issues. 

It defaults beneath when testing on a pseduo-mobile experience in Chrome, but I think this is fine since the real estate on the screen is different.
