### ISSUE TITLE
New header image on Resources page to replace generic blue box

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#16]
Let me know if you need a different size.
![image](https://user-images.githubusercontent.com/12399083/111705595-383e9300-87fe-11eb-9e20-ec6a95889452.png)

**Comment by vannizhang** [comment]
@lisaberrygis Fixed, please test on DEV: https://livingatlasdev.arcgis.com/policy/resources/

**Comment by lisaberrygis** [comment]
Looks awesome. Tried it at different screen sizes and it looked good. I will show the team on Thursday to get their reaction.

My only comment/concern is that the text is a bit hard to read. Is there any way to create more of a halo around the text? Or to use a box like on the Overview page? Otherwise, I may try using a different map.

**Comment by lisaberrygis** [comment]
![image](https://user-images.githubusercontent.com/12399083/112068451-2e32d200-8b27-11eb-81d5-364cff392777.png)

**Comment by lisaberrygis** [comment]
Looks good. No issues on desktop or mobile.
