### ISSUE TITLE
Create hover-text for map titles within Explore tab

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#18]
In the Explore tab, if a map's title is longer than the space allowed in the window, there is no way to see the entire title. 

Ideally, the user could hover over the map title in order to see the full title.
![image](https://user-images.githubusercontent.com/12399083/112033503-b8b10c80-8afa-11eb-8ff8-ce22345ea96c.png)

**Comment by vannizhang** [comment]
@lisaberrygis Please test on DEV: https://livingatlasdev.arcgis.com/policy/browse/?col=41382383bfb24985b7e83532a77c14c8&hs=0&viz=41382383bfb24985b7e83532a77c14c8&loc=-95.319,38.6,3

**Comment by lisaberrygis** [comment]
Looks good. Is there a reason titles seem to cut off when there's still space? Is this a character limit or a space limit? 
![image](https://user-images.githubusercontent.com/12399083/112061711-1e61c080-8b1c-11eb-9648-bf5eacfba672.png)

**Comment by lisaberrygis** [comment]
@vannizhang can the hover text also be added to the summary text?
