### ISSUE TITLE
Add hover text to map title on Explore tab

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#21]
When a title is long, it is getting cut off. Add hover text for the title on the Explore tab header.

![image](https://user-images.githubusercontent.com/12399083/112910338-03f18f00-90a8-11eb-9a6c-b597d38662d3.png)

**Comment by vannizhang** [comment]
@lisaberrygis fixed

**Comment by lisaberrygis** [comment]
Looks good.
