### ISSUE TITLE
Look into window sizing issues

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#22]
These seems to be happening mostly in mobile view.

Explore tab:
![image](https://user-images.githubusercontent.com/12399083/112910440-37ccb480-90a8-11eb-879c-981fdc552037.png)
Issues tab:
![image](https://user-images.githubusercontent.com/12399083/112910460-3f8c5900-90a8-11eb-8e94-5c23e04dce47.png)
Resource tab:
![image](https://user-images.githubusercontent.com/12399083/112910546-6b0f4380-90a8-11eb-9abb-5affea69ce48.png)
Home tab:
![image](https://user-images.githubusercontent.com/12399083/112910581-82e6c780-90a8-11eb-8ab4-86cd5211e3ea.png)

**Comment by lisaberrygis** [comment]
All changes look good except for when the map is open on the Explore tab and the Legend takes over when the screen is made smaller:
![image](https://user-images.githubusercontent.com/12399083/113216764-aa1cd080-9231-11eb-9cad-ed005386137c.png)

**Comment by vannizhang** [comment]
@lisaberrygis fixed this issue by setting the mode property for the Expand Widget to "floating" to always display the widget as floating regardless of browser size.

**Comment by lisaberrygis** [comment]
Looks good. Not seeing any showstoppers.
