### ISSUE TITLE
Add a share component to the mobile experience

### ISSUE THREAD

**Issue by lisaberrygis** [vannizhang/policymaps-new#24]
Add a box to allow users to share URL, twitter, email, facebook

**Comment by vannizhang** [comment]
@lisaberrygis add Share Modal component for mobile view.

**Comment by lisaberrygis** [comment]
@vannizhang, I collected 3 maps and then used the "copy link" feature and it gave me a URL which only one map shows: [](https://livingatlasdev.arcgis.com/policy/browse/?col=787722665db94bfa80fe36bd38848430,6a9dcde9c7e44ba08f3ca4deb2877e7f&hs=1&viz=45e6bb0c0960449cb29031f590af9a59&loc=-96.076,37.535,4)

**Comment by vannizhang** [comment]
@lisaberrygis yes there was a bug, thanks for catching it, should be fixed now.

**Comment by lisaberrygis** [comment]
@vannizhang Looks fixed. A few small comments:

Can this say "Share your collection of maps" so that they know what they are sharing? 
![image](https://user-images.githubusercontent.com/12399083/113331724-24eaf780-92d5-11eb-9bc7-426e46820c5f.png)

I noticed something that isn't specific to the mobile experience, but the twitter sharing option looks like it has a typo. Sharing through email says "Esri Policy Maps" and this says "esri policymaps site". Can we update the twitter text to say "Policy maps for your consideration from the Esri Maps for Public Policy site <URL> #policymaps"
![image](https://user-images.githubusercontent.com/12399083/113332185-b35f7900-92d5-11eb-9330-f0b9d7417d87.png)

**Comment by vannizhang** [comment]
@lisaberrygis Fixed!

**Comment by lisaberrygis** [comment]
@vannizhang Looks good! Looks alot cleaner. My final and only remaining comment is similar but about the email. It seems like there are a few too many newlines from the "legislative research:" and the URL:

![image](https://user-images.githubusercontent.com/12399083/113336063-ab560800-92da-11eb-97f2-3b353421c27d.png)

**Comment by lisaberrygis** [comment]
Looks good. No issues.
